apiVersion: "pipelinesascode.tekton.dev/v1alpha1"
kind: Repository
metadata:
  name: ufu07m0ir-java-quarkus-gitops-repository
spec:
  url: https://github.com/rhtap-rhdh-qe/ufu07m0ir-java-quarkus-gitops