apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: ufu07m0ir-java-quarkus
  janus-idp.io/tekton: ufu07m0ir-java-quarkus
  backstage.io/kubernetes-id: ufu07m0ir-java-quarkus
  backstage.io/kubernetes-namespace: tssc-app 
  app.kubernetes.io/part-of: ufu07m0ir-java-quarkus
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
